name: Flutter CI & Release

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: "Build type for manual run (release or debug)"
        required: false
        default: "debug"
        type: choice
        options:
          - debug
          - release
  push:
    branches:
      - develop
    tags:
      - '*'

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install dependencies
        run: flutter pub get

      # 任意构建场景都准备 keystore 和 key.properties（如果 secrets 存在）
      - name: Prepare keystore and key.properties
        if: env.ANDROID_KEYSTORE_BASE64 != '' && env.ANDROID_KEYSTORE_PASSWORD != '' && env.ANDROID_KEY_ALIAS != '' && env.ANDROID_KEY_PASSWORD != ''
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > android/app/my-release-key.keystore
          cat > android/key.properties <<EOF
          storePassword=$ANDROID_KEYSTORE_PASSWORD
          keyPassword=$ANDROID_KEY_PASSWORD
          keyAlias=$ANDROID_KEY_ALIAS
          storeFile=../app/my-release-key.keystore
          EOF

      # develop分支用debug，tag用release，手动可选
      - name: Build Android APK (Dev)
        if: github.ref == 'refs/heads/develop'
        run: flutter build apk --debug

      - name: Build Android APK (Release)
        if: github.ref_type == 'tag'
        run: flutter build apk --release

      - name: Build Android APK (Manual)
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [ "${{ github.event.inputs.build_type }}" = "release" ]; then
            flutter build apk --release
          else
            flutter build apk --debug
          fi

      - name: Upload Android APK (Dev)
        if: github.ref == 'refs/heads/develop'
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Upload Android APK (Release)
        if: github.ref_type == 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Android APK (Manual)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ github.event.inputs.build_type }}.apk
          path: build/app/outputs/flutter-apk/app-${{ github.event.inputs.build_type }}.apk

      # 仅tag触发时，上传APK到GitHub Release
      - name: Upload APK to GitHub Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          rm -rf Podfile.lock && pod install --repo-update

      # develop分支打debug
      - name: Build iOS (Dev)
        if: github.ref == 'refs/heads/develop'
        run: flutter build ios --debug --no-codesign

      # tag打release
      - name: Build iOS (Release, unsigned)
        if: github.ref_type == 'tag'
        run: flutter build ios --release --no-codesign

      # 手动触发，可选debug/release
      - name: Build iOS (Manual)
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [ "${{ github.event.inputs.build_type }}" = "release" ]; then
            flutter build ios --release --no-codesign
          else
            flutter build ios --debug --no-codesign
          fi

      # 统一制作ipa（所有场景）
      - name: Create IPA from Runner.app (Dev)
        if: github.ref == 'refs/heads/develop'
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r ios-debug.ipa Payload
          rm -rf Payload

      - name: Create IPA from Runner.app (Release)
        if: github.ref_type == 'tag'
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r ios-release.ipa Payload
          rm -rf Payload

      - name: Create IPA from Runner.app (Manual)
        if: github.event_name == 'workflow_dispatch'
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r ios-manual.ipa Payload
          rm -rf Payload

      # 上传ipa，name带后缀
      - name: Upload iOS IPA (Dev)
        if: github.ref == 'refs/heads/develop'
        uses: actions/upload-artifact@v4
        with:
          name: ios-debug.ipa
          path: ios-debug.ipa

      - name: Upload iOS IPA (Release, unsigned)
        if: github.ref_type == 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: ios-release.ipa
          path: ios-release.ipa

      - name: Upload iOS IPA (Manual)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: ios-manual.ipa
          path: ios-manual.ipa

      # tag场景自动发布release
      - name: Upload iOS IPA to GitHub Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          files: ios-release.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
