name: Flutter CI & Release

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: "Build type for manual run (release or debug)"
        required: false
        default: "debug"
        type: choice
        options:
          - debug
          - release
  push:
    branches:
      - develop
    tags:
      - '*'

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Install dependencies
        run: flutter pub get

      # 任意构建场景都准备 keystore 和 key.properties（如果 secrets 存在）
      - name: Prepare keystore and key.properties
        if: env.ANDROID_KEYSTORE_BASE64 != '' && env.ANDROID_KEYSTORE_PASSWORD != '' && env.ANDROID_KEY_ALIAS != '' && env.ANDROID_KEY_PASSWORD != ''
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > android/app/my-release-key.keystore
          cat > android/key.properties <<EOF
          storePassword=$ANDROID_KEYSTORE_PASSWORD
          keyPassword=$ANDROID_KEY_PASSWORD
          keyAlias=$ANDROID_KEY_ALIAS
          storeFile=../app/my-release-key.keystore
          EOF

      # develop分支用debug，tag用release，手动可选
      - name: Build Android APK (Dev)
        if: github.ref == 'refs/heads/develop'
        run: flutter build apk --debug

      - name: Build Android APK (Release)
        if: github.ref_type == 'tag'
        run: flutter build apk --release

      - name: Build Android APK (Manual)
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [ "${{ github.event.inputs.build_type }}" = "release" ]; then
            flutter build apk --release
          else
            flutter build apk --debug
          fi

      - name: Upload Android APK (Dev)
        if: github.ref == 'refs/heads/develop'
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-dev
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Upload Android APK (Release)
        if: github.ref_type == 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Android APK (Manual)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-manual
          path: |
            build/app/outputs/flutter-apk/app-${{ github.event.inputs.build_type }}.apk

  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Install dependencies
        run: flutter pub get

      # develop分支与tag均为不签名打包
      - name: Build iOS (Dev)
        if: github.ref == 'refs/heads/develop'
        run: flutter build ios --debug --no-codesign

      - name: Build iOS (Release, unsigned)
        if: github.ref_type == 'tag'
        run: flutter build ios --release --no-codesign

      # 手动触发，根据 build_type 参数构建 debug 或 release
      - name: Build iOS (Manual)
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [ "${{ github.event.inputs.build_type }}" = "release" ]; then
            flutter build ios --release --no-codesign
          else
            flutter build ios --debug --no-codesign
          fi

      - name: Upload iOS build (Dev)
        if: github.ref == 'refs/heads/develop'
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-dev
          path: build/ios/iphoneos/Runner.app

      - name: Upload iOS build (Release, unsigned)
        if: github.ref_type == 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-release
          path: build/ios/iphoneos/Runner.app

      - name: Upload iOS build (Manual)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-manual
          path: build/ios/iphoneos/Runner.app
